### ISSUE TITLE
Activate plugin and... nothing

### ISSUE THREAD

**Issue by gunn4r** [mcguffin/say-cheese#2]
Hi! I installed the plugin and activated it. There are no new options in the media library, or media uploader pertaining to webcam snapshots. Any ideas?

**Comment by mcguffin** [comment]
@senlin, @gunn4r  It's been a long time since, but anway: Yesterday I added a snapshot / recorder button to the media library (grid view only). I didn't find the time for a code cleanup and proper localization yet, but feel free to test and give feedback.

**Comment by gunn4r** [comment]
Awesome! I'll check it out!
