### ISSUE TITLE
Unable to Snap Webcam or Paste Data

### ISSUE THREAD

**Issue by ansonphong** [mcguffin/say-cheese#7]
Hi, 
This is a very promising plugin, which I'm very much looking forward to use. Both modes of adding images aren't working for me right now though, using **Mac OSX Yosemite**, and **Chrome 42.**
### Webcam Record

![image](https://cloud.githubusercontent.com/assets/4825055/7716826/d2bbe898-fe65-11e4-848f-3bcf6ccbf076.png)

On webcam record, there is no button to actually snap a shot, and so all I can do is look at myself.
### Copy & Paste

![image](https://cloud.githubusercontent.com/assets/4825055/7716845/290e4f38-fe66-11e4-8c24-0fecab557ec0.png)

I can see there's a blinking cursor, though if I try to copy / paste image data from Photoshop or OSX screenshot, absolutely nothing happens. No Javascript Errors either.

I'm guessing this doesn't work on either Mac or Chrome? Is there a fix scheduled for this?

Thanks.

**Comment by mcguffin** [comment]
Hi, 
I just gave it check in Chrome 42 on Yosemite, and it works perfectly for commit ada13036ca0cd1b8d077aace5900fe8e8aa069db.
There might be another WP plugin breaking it or possibly a browser addon or adblocker. Would you mind to do some more testing? I'd love to fix it — or at least document the incompatibilities.
Thanks

**Comment by phongmedia** [comment]
Thanks, good to know. I can do some testing with it.

I just realized that the plugin also broke the normal uploading and media library as well. I'll see if I can find what it is - it could possibly be the theme I'm working with. I'll test it with different themes and plugin configurations.
